### ISSUE TITLE
About PWC-Net

### ISSUE THREAD

**Issue by dawei03896** [yjzhang96/UTI-VFI#1]
Hi, thank you for your wonderful job. I saw "we estimate all the optical flows using the state-of-the-art PWC-Net" in the paper, but I don't see it in use in the code and I did not understand the role of optical flow in the method.

**Comment by yjzhang96** [comment]
First, we did apply PWCNet when we need to obtain optical flow between two adjacent frames, which can be found in ```models/inter_models/UTI_model.py```. Second, our interpolation method is basically an optical flow-based method, which requires the pipeline of "estimate the optical flow of input frames -> calculate the flow for warping -> warp the input frame to the targeting time step". So, yes, the role of optical flow is important in the pipeline, yet we do not elaborate in our paper because it's not our contribution. I recommend you this paper [1] for further information.

[1] Xu, X., Siyao, L., Sun, W., Yin, Q., & Yang, M. H. (2019). Quadratic video interpolation. arXiv preprint arXiv:1911.00627.
